name: Deploy to Production

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  # pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Persist npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist Eleventy .cache
        uses: actions/cache@v4
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - run: npm install
      - run: npx @11ty/eleventy
      # NOTE: here it forks from deploy-to-ghpages.yml
      # copy all relevant files to "_production"
      - name: prepare publish_dir
        run: |
          pwd
          mkdir _production
          cp archive/*.html _production/
          cp -r archive/2025 _production/2025
          ls -la _production
      - name: Deploy to htdocs-2025
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: libregraphicsmeeting/htdocs-2025
          publish_branch: main  # default: gh-pages
          publish_dir: ./_production # this repository/source dir
          destination_dir: public # target repository/target dir
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
